module.exports = {
  FILES_REQUIRED: 'Files array is required',
  USER_ID_REQUIRED: 'User ID is required',
  FOLDER_NOT_FOUND: 'Folder not found or access denied',
  NO_WRITE_PERMISSION: 'You do not have write permission for this folder',
  NO_EDIT_PERMISSION: 'You do not have permission to edit this document',
  NO_MOVE_PERMISSION: 'You do not have permission to move document to this folder',
  DOCUMENT_NOT_FOUND: 'Document not found',
  ACCESS_DENIED: 'Access denied',
  ONLY_OWNER_CAN_DELETE: 'Only document owner can delete documents',
  ONLY_OWNER_CAN_ADD_LABELS: 'Only document owner can add labels',
  ONLY_OWNER_CAN_REMOVE_LABELS: 'Only document owner can remove labels',
  LABEL_NAME_REQUIRED: 'Label name is required',
  LABEL_NAME_TOO_LONG: 'Label name too long (max 50 characters)',
  LABEL_NAME_EXISTS: 'Label with this name already exists',
  LABEL_NOT_FOUND: 'Label not found',
  LABEL_NAME_EMPTY: 'Label name cannot be empty',
  NO_UPDATES_PROVIDED: 'No updates provided',
  ONLY_OWNER_CAN_SHARE: 'Only folder owner can share folders',
  INVALID_PERMISSION_LEVEL: 'Invalid permission level',
  CANNOT_SHARE_WITH_SELF: 'Cannot share folder with yourself',
  ONLY_OWNER_CAN_UPDATE_PERMISSIONS: 'Only folder owner can update permissions',
  ONLY_OWNER_CAN_REVOKE_PERMISSIONS: 'Only folder owner can revoke permissions',
  PERMISSION_NOT_FOUND: 'Permission not found for this user',
  ONLY_OWNER_CAN_VIEW_PERMISSIONS: 'Only folder owner can view permissions',
};
